# Japanese message translation file for plpython
# Copyright (C) 2022 PostgreSQL Global Development Group
# This file is distributed under the same license as the pg_archivecleanup (PostgreSQL) package.
# Honda Shigehiro <honda@postgresql.jp>, 2012.
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL 15)\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2019-06-11 11:34+0900\n"
"PO-Revision-Date: 2021-08-25 17:42+0900\n"
"Last-Translator: Kyotaro Horiguchi <horikyota.ntt@gmail.com>\n"
"Language-Team: Japan PostgreSQL Users Group <jpug-doc@ml.postgresql.jp>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Poedit 1.8.13\n"

#: plpy_cursorobject.c:78
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor は問い合わせもしくは実行計画を期待していました"

#: plpy_cursorobject.c:161
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor は第二引数としてシーケンスを取ります"

#: plpy_cursorobject.c:177 plpy_spi.c:211
#, c-format
msgid "could not execute plan"
msgstr "実行計画を実行できませんでした"

#: plpy_cursorobject.c:180 plpy_spi.c:214
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "%d 個の引数のシーケンスを期待していましたが、個数は %d でした：%s"

#: plpy_cursorobject.c:329
#, c-format
msgid "iterating a closed cursor"
msgstr "反復利用しようとしているカーソルは、すでにクローズされています"

#: plpy_cursorobject.c:337 plpy_cursorobject.c:403
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr ""
"中断されたサブトランザクションの中でカーソルを反復利用しようとしています"

#: plpy_cursorobject.c:395
#, c-format
msgid "fetch from a closed cursor"
msgstr "クローズされたカーソルからのフェッチ"

#: plpy_cursorobject.c:438 plpy_spi.c:409
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "問い合わせの結果に含まれる行数が、Pythonのリストに対して多すぎます"

#: plpy_cursorobject.c:490
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr ""
"中断されたサブトランザクションの中でカーソルをクローズしようとしています"

#: plpy_elog.c:129 plpy_elog.c:130 plpy_plpymodule.c:553
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:143
#, c-format
msgid "unsupported set function return mode"
msgstr "非サポートの集合関数リターンモードです。"

#: plpy_exec.c:144
#, c-format
msgid ""
"PL/Python set-returning functions only support returning one value per call."
msgstr ""
"集合を返却するPL/Python関数では、1回の呼び出しに対して1つの値を返すことのみが"
"サポートされています。"

#: plpy_exec.c:157
#, c-format
msgid "returned object cannot be iterated"
msgstr "返されたオブジェクトは反復利用できません"

#: plpy_exec.c:158
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"PL/Pythonの集合を返す関数は、反復処理可能なオブジェクトを返さなければなりませ"
"ん。"

#: plpy_exec.c:172
#, c-format
msgid "error fetching next item from iterator"
msgstr "反復子から次の項目を取り出せませんでした"

#: plpy_exec.c:215
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "PL/Python プロシージャが None を返しませんでした"

#: plpy_exec.c:219
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "戻り値が\"void\"型である PL/Python関数がNoneを返しませんでした"

#: plpy_exec.c:375 plpy_exec.c:401
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "トリガプロシージャから期待しない戻り値が返されました"

#: plpy_exec.c:376
#, c-format
msgid "Expected None or a string."
msgstr "None もしくは文字列を期待していました。"

#: plpy_exec.c:391
#, c-format
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"PL/Python トリガ関数が、DELETE トリガで \"MODIFY\" を返しました-- 無視します"

#: plpy_exec.c:402
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "None, \"OK\", \"SKIP\", \"MODIFY\" のいずれかを期待していました。"

#: plpy_exec.c:452
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "引数を設定する際に、PyList_SetItem() に失敗しました"

#: plpy_exec.c:456
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "引数を設定する際に、PyDict_SetItemString() に失敗しました"

#: plpy_exec.c:468
#, c-format
msgid ""
"function returning record called in context that cannot accept type record"
msgstr ""
"レコード型を受け付けられないコンテキストでレコードを返す関数が呼び出されまし"
"た"

#: plpy_exec.c:685
#, c-format
msgid "while creating return value"
msgstr "戻り値を生成する際に"

#: plpy_exec.c:919
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] は削除されました。行を変更できません。"

#: plpy_exec.c:924
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] は辞書ではありません"

#: plpy_exec.c:951
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "TD[\"new\"] 辞書の%d番目のキーが文字列ではありません"

#: plpy_exec.c:958
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"TD[\"new\"] で見つかったキー \"%s\" は、行レベルトリガにおけるカラムとしては"
"存在しません"

#: plpy_exec.c:963
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "システム属性\"%s\"は設定できません"

#: plpy_exec.c:968
#, c-format
#| msgid "cannot alter inherited column \"%s\""
msgid "cannot set generated column \"%s\""
msgstr "生成列\"%s\"は設定できません"

#: plpy_exec.c:1026
#, c-format
msgid "while modifying trigger row"
msgstr "トリガ行を変更する際に"

#: plpy_exec.c:1087
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "終了していないサブトランザクションを強制的にアボートしています"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "セッションに複数の Python ライブラリが存在します"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "1個のセッション中で使えるPythonのメジャーバージョンは1種類だけです。"

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "初期化中に捕捉できないエラーがありました"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "\"__main__\" モジュールをインポートできませんでした"

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "グローバル変数(globals)を初期化できませんでした"

#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "PL/Pythonプロシージャ\"%s\""

#: plpy_main.c:402
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python関数\"%s\""

#: plpy_main.c:410
#, c-format
msgid "PL/Python anonymous code block"
msgstr "PL/Pythonの無名コードブロック"

#: plpy_plpymodule.c:186 plpy_plpymodule.c:189
#, c-format
msgid "could not import \"plpy\" module"
msgstr "\"plpy\"モジュールをインポートできませんでした"

#: plpy_plpymodule.c:204
#, c-format
msgid "could not create the spiexceptions module"
msgstr "spiexceptionsモジュールを生成できませんでした"

#: plpy_plpymodule.c:212
#, c-format
msgid "could not add the spiexceptions module"
msgstr "spiexceptionsモジュールを追加できませんでした"

#: plpy_plpymodule.c:280
#, c-format
msgid "could not generate SPI exceptions"
msgstr "SPI例外を生成できませんでした"

#: plpy_plpymodule.c:448
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "plpy.elogで引数を展開できませんでした"

#: plpy_plpymodule.c:457
msgid "could not parse error message in plpy.elog"
msgstr "plpy.elogでエラーメッセージをパースできませんでした"

#: plpy_plpymodule.c:474
#, c-format
msgid "argument 'message' given by name and position"
msgstr "名前と位置で 'message' 引数が渡されました"

#: plpy_plpymodule.c:501
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "この関数に対して'%s'は無効なキーワード引数です"

#: plpy_plpymodule.c:512 plpy_plpymodule.c:518
#, c-format
msgid "invalid SQLSTATE code"
msgstr "無効なSQLSTATEコードです"

#: plpy_procedure.c:230
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "トリガー関数はトリガーとしてのみ呼び出せます"

#: plpy_procedure.c:234
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python関数は%s型を返せません"

#: plpy_procedure.c:312
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python関数は%s型を受け付けられません"

#: plpy_procedure.c:402
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "PL/Python関数\"%s\"をコンパイルできませんでした"

#: plpy_procedure.c:405
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "PL/Python無名コードブロックをコンパイルできませんでした"

#: plpy_resultobject.c:121 plpy_resultobject.c:147 plpy_resultobject.c:173
#, c-format
msgid "command did not produce a result set"
msgstr "コマンドは結果セットを生成しませんでした"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "plpy.prepareの第二引数はシーケンスでなければなりません"

#: plpy_spi.c:104
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: %d 番目の型名が文字列ではありません"

#: plpy_spi.c:176
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute は問い合わせもしくは実行計画を期待していました"

#: plpy_spi.c:195
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute は第二引数としてシーケンスを取ります"

#: plpy_spi.c:305
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan が失敗しました: %s"

#: plpy_spi.c:347
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute が失敗しました: %s"

#: plpy_subxactobject.c:97
#, c-format
msgid "this subtransaction has already been entered"
msgstr "すでにこのサブトランザクションの中に入っています"

#: plpy_subxactobject.c:103 plpy_subxactobject.c:161
#, c-format
msgid "this subtransaction has already been exited"
msgstr "このサブトランザクションからすでに抜けています"

#: plpy_subxactobject.c:155
#, c-format
msgid "this subtransaction has not been entered"
msgstr "このサブトランザクションには入っていません"

#: plpy_subxactobject.c:167
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "抜けるべきサブトランザクションがありません"

#: plpy_typeio.c:591
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "Decimalコンストラクタのためのモジュールをインポートできませんでした"

#: plpy_typeio.c:595
#, c-format
msgid "no Decimal attribute in module"
msgstr "モジュールの中にDecimal属性が含まれていません"

#: plpy_typeio.c:601
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "numericからDecimalへの変換に失敗しました"

#: plpy_typeio.c:915
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "Pythonオブジェクトのバイト表現を生成できませんでした"

#: plpy_typeio.c:1063
#, c-format
msgid "could not create string representation of Python object"
msgstr "Pythonオブジェクトの文字列表現を生成できませんでした"

#: plpy_typeio.c:1074
#, c-format
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""
"Pythonオブジェクトをcstringに変換できませんでした: Pythonの文字列表現にnullバ"
"イトが含まれているようです"

#: plpy_typeio.c:1183
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "配列の次元数が制限値(%d)を超えています"

#: plpy_typeio.c:1187
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "関数の戻り値について、シーケンスの長さを決定できませんでした"

#: plpy_typeio.c:1190 plpy_typeio.c:1194
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "配列のサイズが制限値を超えています"

#: plpy_typeio.c:1220
#, c-format
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr "配列型を返す関数の戻り値がPythonのシーケンスではありません"

#: plpy_typeio.c:1266
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "内部シーケンスで長さが異常です: 長さは%dですが、期待する値は%dでした"

#: plpy_typeio.c:1268
#, c-format
msgid ""
"To construct a multidimensional array, the inner sequences must all have the "
"same length."
msgstr ""
"多次元配列を生成する場合、内部シーケンスはすべて同じ長さでなければなりませ"
"ん。"

#: plpy_typeio.c:1347
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "不正な形式のレコードリテラル: \"%s\""

#: plpy_typeio.c:1348
#, c-format
msgid "Missing left parenthesis."
msgstr "左括弧がありません。"

#: plpy_typeio.c:1349 plpy_typeio.c:1550
#, c-format
msgid ""
"To return a composite type in an array, return the composite type as a "
"Python tuple, e.g., \"[('foo',)]\"."
msgstr ""
"複合型を配列に入れて返したい場合、 \"[('foo',)]\" のように複合型を Pythonのタ"
"プルとして返すようにしてください。"

#: plpy_typeio.c:1396
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "マッピング上にキー\"%s\"が見つかりません"

#: plpy_typeio.c:1397
#, c-format
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"カラムにnullを入れて返す場合、カラム名をキーとして値がNoneのエントリをマッピ"
"ングに追加してください。"

#: plpy_typeio.c:1450
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "返されたシーケンスの長さが行のカラム数とマッチしませんでした"

#: plpy_typeio.c:1548
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "属性\"%s\"がPythonオブジェクト中に存在しません"

#: plpy_typeio.c:1551
#, c-format
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"カラムにnullを入れて返す場合、カラム名をキーとして値がNoneである属性を持つオ"
"ブジェクトを返すようにしてください。"

#: plpy_util.c:35
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "PythonのUnicodeオブジェクトをバイト列に変換できませんでした"

#: plpy_util.c:41
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "エンコードされた文字列からバイト列を抽出できませんでした"
