# Brazilian Portuguese message translation file for plpython
#
# Copyright (C) 2009-2022 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
#
# Euler Taveira <euler@eulerto.com>, 2009-2022.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 15\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2022-09-27 13:15-0300\n"
"PO-Revision-Date: 2009-05-10 01:15-0300\n"
"Last-Translator: Euler Taveira <euler@eulerto.com>\n"
"Language-Team: Brazilian Portuguese <pgsql-translators@postgresql.org>\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n>1);\n"

#: plpy_cursorobject.c:72
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor esperava uma consulta ou um plano"

#: plpy_cursorobject.c:155
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor tem uma sequência como seu segundo argumento"

#: plpy_cursorobject.c:171 plpy_spi.c:205
#, c-format
msgid "could not execute plan"
msgstr "não pôde executar plano"

#: plpy_cursorobject.c:174 plpy_spi.c:208
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequência esperada de %d argumento, recebeu %d: %s"
msgstr[1] "Sequência esperada de %d argumentos, recebeu %d: %s"

#: plpy_cursorobject.c:321
#, c-format
msgid "iterating a closed cursor"
msgstr "iterando um cursor fechado"

#: plpy_cursorobject.c:329 plpy_cursorobject.c:395
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "iterando um cursor em uma subtransação abortada"

#: plpy_cursorobject.c:387
#, c-format
msgid "fetch from a closed cursor"
msgstr "busca em um cursor fechado"

#: plpy_cursorobject.c:430 plpy_spi.c:401
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "resultado da consulta tem muitos registros para caber em uma lista Python"

#: plpy_cursorobject.c:482
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "fechando um cursor em uma subtransação abortada"

#: plpy_elog.c:125 plpy_elog.c:126 plpy_plpymodule.c:530
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:139
#, c-format
msgid "unsupported set function return mode"
msgstr "modo de retorno da função que retorna conjunto não é suportado"

#: plpy_exec.c:140
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "funções PL/Python que retornam conjunto só suportam retornar um valor por chamada."

#: plpy_exec.c:153
#, c-format
msgid "returned object cannot be iterated"
msgstr "objeto retornado não pode ser iterado"

#: plpy_exec.c:154
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "funções PL/Python que retornam conjunto devem retornar um objeto iterável."

#: plpy_exec.c:168
#, c-format
msgid "error fetching next item from iterator"
msgstr "erro ao buscar próximo item do iterador"

#: plpy_exec.c:211
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "procedimento PL/Python não retornou None"

#: plpy_exec.c:215
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "função PL/Python com tipo de retorno \"void\" não retornou None"

#: plpy_exec.c:369 plpy_exec.c:395
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "função de gatilho retornou valor inesperado"

#: plpy_exec.c:370
#, c-format
msgid "Expected None or a string."
msgstr "None ou uma cadeia de caracteres era esperado."

#: plpy_exec.c:385
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "função de gatilho PL/Python retornou \"MODIFY\" em um gatilho DELETE -- ignorado"

#: plpy_exec.c:396
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Era esperado None, \"OK\", \"SKIP\" ou \"MODIFY\"."

#: plpy_exec.c:441
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() falhou ao definir argumentos"

#: plpy_exec.c:445
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() falhou ao definir argumentos"

#: plpy_exec.c:457
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "função que retorna record foi chamada em um contexto que não pode aceitar tipo record"

#: plpy_exec.c:674
#, c-format
msgid "while creating return value"
msgstr "ao criar valor de retorno"

#: plpy_exec.c:908
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] removido, não pode modificar registro"

#: plpy_exec.c:913
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] não é um dicionário"

#: plpy_exec.c:938
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "chave do dicionário TD[\"new\"] na posição %d não é uma cadeia de caracteres"

#: plpy_exec.c:945
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "chave \"%s\" encontrada em TD[\"new\"] não existe como uma coluna no registro do gatilho"

#: plpy_exec.c:950
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "não pode definir atributo do sistema \"%s\""

#: plpy_exec.c:955
#, c-format
msgid "cannot set generated column \"%s\""
msgstr "não pode definir coluna gerada \"%s\""

#: plpy_exec.c:1013
#, c-format
msgid "while modifying trigger row"
msgstr "ao modificar registro de gatilho"

#: plpy_exec.c:1071
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "forçado a abortar subtransação que não foi concluída"

#: plpy_main.c:111
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "múltiplas bibliotecas do Python estão presentes na sessão"

#: plpy_main.c:112
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Apenas uma versão do Python pode ser utilizada na sessão."

#: plpy_main.c:124
#, c-format
msgid "untrapped error in initialization"
msgstr "erro não interceptado na inicialização"

#: plpy_main.c:147
#, c-format
msgid "could not import \"__main__\" module"
msgstr "não pôde importar módulo \"__main__\""

#: plpy_main.c:156
#, c-format
msgid "could not initialize globals"
msgstr "não pôde inicializar globais"

#: plpy_main.c:354
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "procedimento PL/Python \"%s\""

#: plpy_main.c:357
#, c-format
msgid "PL/Python function \"%s\""
msgstr "função PL/Python \"%s\""

#: plpy_main.c:365
#, c-format
msgid "PL/Python anonymous code block"
msgstr "bloco de código PL/Python anônimo"

#: plpy_plpymodule.c:168 plpy_plpymodule.c:171
#, c-format
msgid "could not import \"plpy\" module"
msgstr "não pôde importar módulo \"plpy\""

#: plpy_plpymodule.c:182
#, c-format
msgid "could not create the spiexceptions module"
msgstr "não pôde criar o módulo spiexceptions"

#: plpy_plpymodule.c:190
#, c-format
msgid "could not add the spiexceptions module"
msgstr "não pôde adicionar o módulo spiexceptions"

#: plpy_plpymodule.c:257
#, c-format
msgid "could not generate SPI exceptions"
msgstr "não pôde gerar exceções da SPI"

#: plpy_plpymodule.c:425
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "não pode desempacotar argumentos em plpy.elog"

#: plpy_plpymodule.c:434
msgid "could not parse error message in plpy.elog"
msgstr "não pode analisar mensagem de erro em plpy.elog"

#: plpy_plpymodule.c:451
#, c-format
msgid "argument 'message' given by name and position"
msgstr "argumento 'message' informado por nome e posição"

#: plpy_plpymodule.c:478
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' é um argumento inválido para esta função"

#: plpy_plpymodule.c:489 plpy_plpymodule.c:495
#, c-format
msgid "invalid SQLSTATE code"
msgstr "código SQLSTATE inválido"

#: plpy_procedure.c:225
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "funções de gatilho só podem ser chamadas como gatilhos"

#: plpy_procedure.c:229
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "funções PL/Python não podem retornar tipo %s"

#: plpy_procedure.c:307
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "funções PL/Python não podem aceitar tipo %s"

#: plpy_procedure.c:397
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "não pôde compilar função PL/Python \"%s\""

#: plpy_procedure.c:400
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "não pôde compilar bloco de código PL/Python anônimo"

#: plpy_resultobject.c:117 plpy_resultobject.c:143 plpy_resultobject.c:169
#, c-format
msgid "command did not produce a result set"
msgstr "comando não produziu um conjunto de resultados"

#: plpy_spi.c:56
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "segundo argumento de plpy.prepare deve ser uma sequência"

#: plpy_spi.c:98
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: nome do tipo na posição %d não é uma cadeia de caracteres"

#: plpy_spi.c:170
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute espera uma consulta ou um plano"

#: plpy_spi.c:189
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute recebe uma sequência como segundo argumento"

#: plpy_spi.c:297
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan falhou: %s"

#: plpy_spi.c:339
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute falhou: %s"

#: plpy_subxactobject.c:92
#, c-format
msgid "this subtransaction has already been entered"
msgstr "essa subtransação já foi iniciada"

#: plpy_subxactobject.c:98 plpy_subxactobject.c:156
#, c-format
msgid "this subtransaction has already been exited"
msgstr "essa subtransação já foi concluída"

#: plpy_subxactobject.c:150
#, c-format
msgid "this subtransaction has not been entered"
msgstr "essa subtransação não foi iniciada"

#: plpy_subxactobject.c:162
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "não há uma subtransação a ser concluída"

#: plpy_typeio.c:587
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "não pôde importar módulo para construtor Decimal"

#: plpy_typeio.c:591
#, c-format
msgid "no Decimal attribute in module"
msgstr "nenhum atributo Decimal no módulo"

#: plpy_typeio.c:597
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "conversão de numeric para Decimal falhou"

#: plpy_typeio.c:911
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "não pôde criar representação de bytes de um objeto Python"

#: plpy_typeio.c:1048
#, c-format
msgid "could not create string representation of Python object"
msgstr "não pôde criar representação de cadeia de caracteres de um objeto Python"

#: plpy_typeio.c:1059
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "não pôde converter objeto Python em cstring: representação de cadeia de caracteres Python parece conter bytes nulos"

#: plpy_typeio.c:1170
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "número de dimensões da matriz excede o máximo permitido (%d)"

#: plpy_typeio.c:1175
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "não pôde determinar tamanho da sequência para valor de retorno da função"

#: plpy_typeio.c:1180 plpy_typeio.c:1186
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "tamanho da matriz excede o máximo permitido"

#: plpy_typeio.c:1214
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "valor de retorno da função do tipo matriz retorna tipo que não é uma sequência Python"

#: plpy_typeio.c:1261
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "tamanho incorreto da sequência interna: tem tamanho %d, mas %d era esperado"

#: plpy_typeio.c:1263
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr "Para construir uma matriz multidimensional, todas as sequências internas devem ter o mesmo tamanho."

#: plpy_typeio.c:1342
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "matriz mal formada: \"%s\""

#: plpy_typeio.c:1343
#, c-format
msgid "Missing left parenthesis."
msgstr "Faltando parêntese esquerdo."

#: plpy_typeio.c:1344 plpy_typeio.c:1545
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Para retornar um tipo composto em uma matriz, retorne o tipo composto como uma tupla do Python, i.e., \"[('foo',)]\"."

#: plpy_typeio.c:1391
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "chave \"%s\" não foi encontrada no mapeamento"

#: plpy_typeio.c:1392
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Para retornar nulo em uma coluna, adicionar o valor None no mapeamento cuja chave é o nome da coluna."

#: plpy_typeio.c:1445
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "tamanho da sequência retornada não combina com número de colunas no registro"

#: plpy_typeio.c:1543
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "atributo \"%s\" não existe no objeto Python"

#: plpy_typeio.c:1546
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Para retornar nulo na coluna, deixe o objeto retornado ter um atributo cuja chave é o nome do coluna e o valor é None."

#: plpy_util.c:31
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "não pôde converter objeto Unicode Python para bytes"

#: plpy_util.c:37
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "não pôde extrair bytes de cadeia de caracteres codificada"
