# LANGUAGE message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2019-04-26 13:38+0000\n"
"PO-Revision-Date: 2019-06-13 17:10+0300\n"
"Last-Translator: Abdullah G. Gülner <agulner@gmail.com>\n"
"Language-Team: Turkish <devrim@gunduz.org>\n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Poedit 1.8.7.1\n"

#: plpy_cursorobject.c:78
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor bir sorgu ya da bir plan bekledi"

#: plpy_cursorobject.c:161
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor bir sequence'ı ikinci argüman olarak alır"

#: plpy_cursorobject.c:177 plpy_spi.c:211
#, c-format
msgid "could not execute plan"
msgstr "plan çalıştırılamadı"

#: plpy_cursorobject.c:180 plpy_spi.c:214
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "%d argümanının sequence'ı beklendi; %d alındı: %s"

#: plpy_cursorobject.c:329
#, c-format
msgid "iterating a closed cursor"
msgstr "kapalı bir imleç (cursor) yineleniyor"

#: plpy_cursorobject.c:337 plpy_cursorobject.c:403
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "iptal edilen bir alt-işlemdeki (subtransaction) bir cursor yineleniyor"

#: plpy_cursorobject.c:395
#, c-format
msgid "fetch from a closed cursor"
msgstr "kapalı bir cursor'dan getir"

#: plpy_cursorobject.c:438 plpy_spi.c:409
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "sorgu sonucundaki satır sayısı bir Python listesine sığabilecekten çok fazla "

#: plpy_cursorobject.c:490
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "iptal edilen bir alt-işlemdeki (subtransaction) bir cursor kapatılıyor"

#: plpy_elog.c:129 plpy_elog.c:130 plpy_plpymodule.c:553
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:143
#, c-format
msgid "unsupported set function return mode"
msgstr "desteklenmeyen küme fonksiyonu dönüş modu"

#: plpy_exec.c:144
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "PL/Python küme dönen fonksiyonları sadece her çağrı içinde bir değer döndürmeyi desteklerler"

#: plpy_exec.c:157
#, c-format
msgid "returned object cannot be iterated"
msgstr "dönen nesne yinelenemez"

#: plpy_exec.c:158
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python küme dönen fonksiyonları yinelenebilir bir nesne dönmelidir."

#: plpy_exec.c:172
#, c-format
msgid "error fetching next item from iterator"
msgstr "yineleticiden sonraki öğeyi alırken hata"

#: plpy_exec.c:215
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "PL/Python prosedürü None döndürmedi"

#: plpy_exec.c:219
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "dönüş tipi \"void\" olan PL/Python fonksiyonu None döndürmedi"

#: plpy_exec.c:375 plpy_exec.c:401
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "trigger yordamından beklenmeyen dönüş değeri"

#: plpy_exec.c:376
#, c-format
msgid "Expected None or a string."
msgstr "None ya da string bekleniyordu."

#: plpy_exec.c:391
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "PL/Python trigger fonksiyonu DELETE triggerında \"MODIFY\" döndürdü -- gözardı edildi"

#: plpy_exec.c:402
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "None, \"OK\", \"SKIP\", ya da \"MODIFY\" bekleniyordu"

#: plpy_exec.c:452
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() bağımsız değişkenler ayarlanırken başarısız oldu"

#: plpy_exec.c:456
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() bağımsız değişkenler ayarlanırken başarısız oldu"

#: plpy_exec.c:468
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "tip kaydı içermeyen alanda çağırılan ve kayıt döndüren fonksiyon"

#: plpy_exec.c:685
#, c-format
msgid "while creating return value"
msgstr "dönüş değeri yaratılırken"

#: plpy_exec.c:919
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] silindi, satır düzenlenemiyor"

#: plpy_exec.c:924
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] bir sözlük değil"

#: plpy_exec.c:951
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "%d sıra pozisyonundaki TD[\"new\"] sözlük anahtarı dizi değil"

#: plpy_exec.c:958
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "TD[\"new\"]  içinde bulunan \"%s\" anahtarı tetikleyen satırda bir kolon olarak bulunmuyor"

#: plpy_exec.c:963
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "\"%s\" sistem niteliği ayarlanamıyor"

#: plpy_exec.c:968
#, c-format
msgid "cannot set generated column \"%s\""
msgstr "oluşturulan \"%s\" sütunu ayarlanamıyor"

#: plpy_exec.c:1026
#, c-format
msgid "while modifying trigger row"
msgstr "tetikleyici satırını düzenlerken"

#: plpy_exec.c:1087
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "çıkış yapılmamış bir alt-işlem (subtransaction) zorla iptal ediliyor"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "oturumda birden çok Python kütüphanesi mevcut"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Bir oturumda sadece bir Python ana sürümü kullanılabilir."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "ilklendirme aşamasında yakalanamayan hata"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "\"__main__\" modülü alınamadı"

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "global değerler ilklendirilemedi"

#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "\"%s\" PL/Python prosedürü"

#: plpy_main.c:402
#, c-format
msgid "PL/Python function \"%s\""
msgstr "\"%s\" PL/Python fonksiyonu"

#: plpy_main.c:410
#, c-format
msgid "PL/Python anonymous code block"
msgstr "PL/Python anonim kod bloğu"

#: plpy_plpymodule.c:186 plpy_plpymodule.c:189
#, c-format
msgid "could not import \"plpy\" module"
msgstr "\"plpy\" modülü alınamadı"

#: plpy_plpymodule.c:204
#, c-format
msgid "could not create the spiexceptions module"
msgstr "spiexceptions modülü oluşturulamadı"

#: plpy_plpymodule.c:212
#, c-format
msgid "could not add the spiexceptions module"
msgstr "spiexceptions modülü eklenemedi"

#: plpy_plpymodule.c:280
#, c-format
msgid "could not generate SPI exceptions"
msgstr "SPI istisnaları (exception) üretilemedi"

#: plpy_plpymodule.c:448
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "plpy.elog dosyasındaki argümanlar unpack edilemedi"

#: plpy_plpymodule.c:457
msgid "could not parse error message in plpy.elog"
msgstr "plpy.elog dosyasındaki hata mesajı ayrıştırılamadı"

#: plpy_plpymodule.c:474
#, c-format
msgid "argument 'message' given by name and position"
msgstr "ad ve konum tarafından verilen argüman 'mesajı'"

#: plpy_plpymodule.c:501
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' bu fonksiyon için geçersiz bir anahtar kelime argümanıdır"

#: plpy_plpymodule.c:512 plpy_plpymodule.c:518
#, c-format
msgid "invalid SQLSTATE code"
msgstr "geçersiz SQLSTATE kodu"

#: plpy_procedure.c:230
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "trigger fonksiyonları sadece trigger olarak çağırılabilirler."

#: plpy_procedure.c:234
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python fonksiyonları %s tipini döndüremezler"

#: plpy_procedure.c:312
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python fonksiyonlar %s tipini kabul etmezler"

#: plpy_procedure.c:402
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "\"%s\" PL/Python fonksiyonu derlenemedi"

#: plpy_procedure.c:405
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "anonim PL/Python kod bloğu derlenemedi"

#: plpy_resultobject.c:121 plpy_resultobject.c:147 plpy_resultobject.c:173
#, c-format
msgid "command did not produce a result set"
msgstr "komut bir sonuç kümesi üretmedi"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "plpy.prepare'in ikinci argümanı sequence olmalıdır"

#: plpy_spi.c:104
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: %d sıra posizyonundaki veri tipi dizi değil"

#: plpy_spi.c:176
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute bir sorgu ya da bir plan bekledi"

#: plpy_spi.c:195
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute bir sequence'ı ikinci argüman olarak alır"

#: plpy_spi.c:305
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan başarısız oldu: %s"

#: plpy_spi.c:347
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute başarısız oldu: %s"

#: plpy_subxactobject.c:97
#, c-format
msgid "this subtransaction has already been entered"
msgstr "bu alt-işleme (subtransaction) zaten girilmiş"

#: plpy_subxactobject.c:103 plpy_subxactobject.c:161
#, c-format
msgid "this subtransaction has already been exited"
msgstr "bu alt-işlemden (subtransaction) zaten çıkılmış"

#: plpy_subxactobject.c:155
#, c-format
msgid "this subtransaction has not been entered"
msgstr "bu alt-işleme (subtransaction) girilmemiş"

#: plpy_subxactobject.c:167
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "çıkılacak bir alt-işlem (subtransaction) yok"

#: plpy_typeio.c:591
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "Decimal constructor için bir modül alınamadı"

#: plpy_typeio.c:595
#, c-format
msgid "no Decimal attribute in module"
msgstr "modülde Decimal niteliği yok"

#: plpy_typeio.c:601
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "numeric'ten Decimal'e dönüşüm başarısız oldu"

#: plpy_typeio.c:915
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "Python nesnesinin bytes gösterimi yaratılamadı"

#: plpy_typeio.c:1063
#, c-format
msgid "could not create string representation of Python object"
msgstr "Python nesnesinin dizgi gösterimi yaratılamadı"

#: plpy_typeio.c:1074
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "Python nesnesi cstring'e dönüştürülemedi: Python dizgi gösterimi null bayt içeriyor olabilir."

#: plpy_typeio.c:1183
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "dizi (array) boyut sayısı izin verilen en yüksek değeri (%d) aşmaktadır"

#: plpy_typeio.c:1187
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "fonksiyon dönüş değeri için sequence uzunluğu belirlenemedi"

#: plpy_typeio.c:1190 plpy_typeio.c:1194
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "dizi (array) boyutu izin verilen en yüksek değeri aşmaktadır"

#: plpy_typeio.c:1220
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "dizi dönüp tipli dönüş değeri olan fonksiyon Python sequence'ı değildir"

#: plpy_typeio.c:1266
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "iç sequence'in uzunluğu yanlış: %d uzunlukta, fakat %d bekleniyordu"

#: plpy_typeio.c:1268
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr "Çok boyutlu bir dizi oluşturmak için, iç sequence'lerin tamamı aynı uzunlukta olmalı."

#: plpy_typeio.c:1347
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "hatalı değer: \"%s\""

#: plpy_typeio.c:1348
#, c-format
msgid "Missing left parenthesis."
msgstr "Sol parantez eksik."

#: plpy_typeio.c:1349 plpy_typeio.c:1550
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Bir bileşik türü dizi (array) içinde döndürmek için, bileşik türü bir Python tuple, e.g., \"[('foo',)]\"."

#: plpy_typeio.c:1396
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "\"%s\" anahtarı planlamada bulunnamadı"

#: plpy_typeio.c:1397
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Bir kolondan Null döndürmek için, kolonun ismindeki eşleşmenin anahtarına, NONE değerini ekleyin"

#: plpy_typeio.c:1450
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "Dönen sequence'in uzunluğu satırdaki kolonların sayısı ile eşleşmiyor."

#: plpy_typeio.c:1548
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "\"%s\" niteliği Python nesnesinde bulunmaz"

#: plpy_typeio.c:1551
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr " Bir kolondan null döndürmek için, döndürdüğünüz nesnenin, kolonun adına sahip bir özelliğinin olmasını ve bu özelliğin değerinin NONE olmasını sağlamanız gerekir"

#: plpy_util.c:35
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "Python unicode nesnesi baytlara dönüştürülemedi."

#: plpy_util.c:41
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "kodlanmış string den baytlar çıkarılamadı"

#~ msgid "could not create new dictionary while building trigger arguments"
#~ msgstr "trigger argümanlarını oluştururken yeni sözlük yaratılamadı"

#~ msgid "could not create globals"
#~ msgstr "evrensel değerler (globals) oluşturulamadı"

#~ msgid "could not create exception \"%s\""
#~ msgstr "\"%s\" istisnası (exception) oluşturulamadı"

#~ msgid "could not create new dictionary"
#~ msgstr "Yeni sözlük yaratılamadı"

#~ msgid "PL/Python function \"%s\" could not execute plan"
#~ msgstr "\"%s\" PL/Python fonksiyonu planı çalıştıramadı"

#~ msgid "PL/Python function \"%s\" failed"
#~ msgstr "\"%s\" PL/Python fonksiyonu başarısız oldu"

#~ msgid "could not create string representation of Python object in PL/Python function \"%s\" while creating return value"
#~ msgstr "dönüş değeri yaratılırken \"%s\" Pl/Python fonksiyonunun içindeki Python ensnesinin dizi gösterimi yaratılamadı"

#~ msgid "could not compute string representation of Python object in PL/Python function \"%s\" while modifying trigger row"
#~ msgstr "tetikleyici satırı düzenlerken \"%s\" PL/Python fonksiyonunun içindeki Python nesnesinin dizi gösterimi hesaplanamadı"

#~ msgid "out of memory"
#~ msgstr "yetersiz bellek"

#~ msgid "PL/Python: %s"
#~ msgstr "PL/Python: %s"

#~ msgid "could not create procedure cache"
#~ msgstr "yordam önbelleği yaratılamadı"

#~ msgid "Start a new session to use a different Python major version."
#~ msgstr "Farklı bir Python ana sürümü kullanmak için yeni bir oturum açın."

#~ msgid "This session has previously used Python major version %d, and it is now attempting to use Python major version %d."
#~ msgstr "Bu oturum daha önceden %d Python ana sürümünü kullandı, ve şimdi %d ana sürümünü kullanmayı deniyor."

#~ msgid "unrecognized error in PLy_spi_execute_fetch_result"
#~ msgstr "PLy_spi_execute_fetch_result içinde tanımlanamayan hata"

#~ msgid "unrecognized error in PLy_spi_execute_query"
#~ msgstr "PLy_spi_execute_query içinde tanımlanamayan hata"

#~ msgid "unrecognized error in PLy_spi_execute_plan"
#~ msgstr "PLy_spi_execute_plan içinde beklenmeyen hata"

#~ msgid "unrecognized error in PLy_spi_prepare"
#~ msgstr "PLy_spi_prepare içinde tanımlanamayan hata"

#~ msgid "plpy.prepare does not support composite types"
#~ msgstr "plpy.prepare kompozit tipleri desteklemez"

#~ msgid "invalid arguments for plpy.prepare"
#~ msgstr "plpy.prepare için geçersiz argümanlar"

#~ msgid "transaction aborted"
#~ msgstr "transaction iptal edildi"

#~ msgid "plan.status takes no arguments"
#~ msgstr "plan.status bir argüman almaz"

#~ msgid "PL/Python only supports one-dimensional arrays."
#~ msgstr "PL/Python sadece bir boyutlu dizileri destekler."

#~ msgid "cannot convert multidimensional array to Python list"
#~ msgstr "çok boyutlu dizi, Python listesine dönüştürülemedi"

#~ msgid "PL/Python does not support conversion to arrays of row types."
#~ msgstr "PL/Python satır tiplerinin dizilere dönüşümünü desteklemez."

#~ msgid "PyCObject_FromVoidPtr() failed"
#~ msgstr "PyCObject_FromVoidPtr() başarısız oldu"

#~ msgid "PyCObject_AsVoidPtr() failed"
#~ msgstr "PyCObject_AsVoidPtr() başarısız oldu"
